export {default as Navbar} from './Navbar/Navbar'
export {default as About} from './About/About'
export {default as Search} from './Search/Search'
export {default as Footer} from './Footer/Footer'
export {default as Contact} from './Contact/Contact'
